### PR TITLE
Update README.md

### PR DESCRIPTION
**Pull request by vdusart**
I added a repo that I made that allows to create automatically the config file for the candymachineV2.

### CODE REVIEW

**Comment by ilmoi** [comment]
your actual PR changes a shit ton of lines - pls clean up to only add the new line, otherwise can't accept

**Comment by vdusart** [comment]
@ilmoi yes because I fixed a lot of broken links but the auto formatting did also some unwanted changes like removing useless space at the end of some lines.
I will fix thoses RN.

**Comment by vdusart** [comment]
Do you still want me to fixe those things ?

**Comment by ilmoi** [comment]
My bad - should have spent more time looking through. I got the impression your IDE did a bunch of auto changes. Will know better next time.

**Comment by vdusart** [comment]
NP, I should have explained my PR better

**Pull request merged**
